version: 2.1

orbs:
 win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default     

    steps:
      - checkout
      - run:
          name: Building NuGet Installer using MSBuild
          command: msbuild NuGetInstaller.sln /m /p:Configuration=Release /p:Platform="Any CPU"