version: 2.1

orbs:
 win: circleci/windows@2.2.0

jobs:
  branches:
    ignore:
      - gh-pages
  build:
    executor: win/default

    steps:
      - checkout
      - run: msbuild NuGetInstaller.sln /m /p:Configuration=Release /p:Platform="Any CPU"
