trigger:
- master

jobs:
- job: Windows

  pool:
    vmImage: 'windows-latest'

  steps:

  - task: MSBuild@1
    inputs:
      solution: 'NugetInstaller.sln'
      platform: 'Any CPU'
      configuration: 'Release'
      maximumCpuCount: true
    displayName: 'Building Nuget Installer using MSBuild'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)\s\CLI\bin\Release\NuGetInstaller.exe'
      artifact: 'NuGet Installer executable file'
      publishLocation: 'pipeline'
    displayName: 'Publish CLI Pipeline Artifacts'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)\s\GUI\bin\Release\NuGetInstaller-GUI.exe'
      artifact: 'NuGet Installer executable file'
      publishLocation: 'pipeline'
    displayName: 'Publish GUI Pipeline Artifacts'
